### ISSUE TITLE
error : Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info

### ISSUE THREAD

**Issue by venkatesh-pro** [mrdbourke/food-not-food#4]
Uncaught (in promise) RuntimeError: abort(undefined). Build with -s ASSERTIONS=1 for more info

I go this error, after converting the tensorflow model into tflite model , only with transfer learning i got this error

![mrdb](https://user-images.githubusercontent.com/74946135/142956894-9fb792fb-bfdc-47db-a89d-e26e57076ac2.png)

**Comment by mrdbourke** [comment]
Hey @venkatesh-pro,

What have you tried so far? 

Which model are you using?

How are you training/converting it?

**Comment by venkatesh-pro** [comment]
Sir I use your food_not_food_model_v0, food_not_food_model_v1, I got error why

**Comment by venkatesh-pro** [comment]
@mrdbourke 
 If I create transfer learning model with tensorflow, I got this same error can you solve this

If I convert tensorflow model into tensorflowjs model, I go this error
![Screenshot (181)](https://user-images.githubusercontent.com/74946135/143420569-9f63e126-2acd-4c90-bd9c-78e9604c444d.png)

**Comment by venkatesh-pro** [comment]
@mrdbourke  iam training the model with your code only 

your code : https://github.com/mrdbourke/tensorflow-deep-learning/blob/main/06_transfer_learning_in_tensorflow_part_3_scaling_up.ipynb


After converting the tensorflow transfer learning  model into tensorflowjs model ,if i load the model in website i got this error, same for tflite model also

✔ if i create model without transfer learning , I didn't get error https://binary-classification-model-cnn.vercel.app/

**Comment by venkatesh-pro** [comment]
@mrdbourke  Please solve this issue sir, it is killing me

**Comment by venkatesh-pro** [comment]
@mrdbourke  sir you got that script error in replit , that what i am showing

**Comment by venkatesh-pro** [comment]
you can see the error by loading 

```javascriptconst model = await tf.loadLayersModel(
        'https://raw.githubusercontent.com/venkatesh-pro/tensorflow-deep-learning-model/main/model.json'
)
```

**Comment by venkatesh-pro** [comment]
if you free also ,we can have a zoom meet , please solve my error 😭😢

**Comment by venkatesh-pro** [comment]
@mrdbourke  sir i found out this error only with the efficient net model, so i use resnet model
